FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o bin-manager ./cmd/manager

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/bin-manager .
COPY --from=builder /app/web ./web
COPY --from=builder /app/internal/config ./internal/config

EXPOSE 8081

CMD ["./bin-manager", "-f", "./internal/config/manager.json"]
